<script setup lang="ts">
import { computed, onMounted, ref } from 'vue'
import { exportBackup, importBackup } from '../features/backup/backupService'
import { formatBytes, getStorageProtectionStatus, requestStorageProtection, type StorageProtectionStatus } from '../features/storage/storageProtection'
import { db } from '../shared/db/database'
import { formatDateTime } from '../shared/format/date'
import { appLock, appUnlocked } from '../features/privacy/appLockStore'
import { createLocalContentRepository } from '../features/storage/localContentRepository'
import { detectSpeechRecognition } from '../features/transcription/transcriptionService'

const storage = ref<StorageProtectionStatus>({ supported: false, persisted: false, usage: null, quota: null }); const busy = ref(false); const message = ref(''); const error = ref('')
const contentRepository = createLocalContentRepository(db)
const percent = computed(() => storage.value.usage !== null && storage.value.quota ? Math.min(100, storage.value.usage / storage.value.quota * 100) : 0)
async function refresh(request = false) { storage.value = request ? await requestStorageProtection() : await getStorageProtectionStatus() }
async function download() { if (storage.value.usage && storage.value.usage > 50 * 1024 * 1024 && !confirm(`预计备份内容约 ${formatBytes(storage.value.usage)}，生成可能需要一些时间，是否继续？`)) return; busy.value = true; error.value = ''; try { const blob = await exportBackup(db); const url = URL.createObjectURL(blob); const link = document.createElement('a'); link.href = url; link.download = `灵感备份-${new Date().toISOString().slice(0, 10)}.zip`; link.click(); URL.revokeObjectURL(url); message.value = `备份已生成：${formatDateTime(new Date().toISOString())}` } catch (value) { const text = value instanceof Error ? value.message : '备份失败'; error.value = /quota|space|storage/iu.test(text) ? '存储空间不足，请先导出已有备份或删除不需要的录音；当前草稿仍会保留' : text } finally { busy.value = false } }
async function restore(event: Event) { const input = event.target as HTMLInputElement; const file = input.files?.[0]; if (!file) return; busy.value = true; error.value = ''; try { const result = await importBackup(file, db); message.value = `恢复完成：导入 ${result.imported} 条，跳过 ${result.skipped} 条，音频 ${result.audio} 个`; await refresh() } catch (value) { error.value = value instanceof Error ? value.message : '恢复失败' } finally { input.value = ''; busy.value = false } }
async function clearAll() { if (!confirm('确定清空全部灵感、标签和录音吗？此操作无法撤销。')) return; if (!confirm('请再次确认：所有本地数据将被永久删除。')) return; await contentRepository.clearAll(); message.value = '全部本地数据已清空'; await refresh() }
async function configureLock() { if (appLock.configured()) { if (!confirm('确定关闭应用锁吗？')) return; appLock.clear(); message.value = '应用锁已关闭'; return }; const pin = prompt('请设置 6 位数字密码') ?? ''; try { await appLock.setup(pin); appUnlocked.value = true; message.value = '应用锁已开启，应用进入后台后会自动锁定' } catch (value) { error.value = value instanceof Error ? value.message : '应用锁设置失败' } }
onMounted(() => refresh())
</script>
<template><main class="page settings-page"><header><h1>设置</h1><p>保护只保存在这台手机里的灵感。</p></header><aside class="risk-note">数据仅保存在当前浏览器。卸载浏览器、清理站点数据或更换手机可能导致数据丢失，请定期导出 ZIP 备份。</aside><h2>隐私与兼容性</h2><section class="setting-card"><button type="button" @click="configureLock">应用锁 · {{ appLock.configured() ? '已开启' : '未开启' }}<small>{{ appLock.configured() ? '进入后台后自动锁定' : '使用 6 位数字密码保护灵感' }}</small></button><div><strong>自动转写 · {{ detectSpeechRecognition() ? '当前浏览器支持' : '当前浏览器不支持' }}</strong><small>{{ detectSpeechRecognition() ? '录音时会尝试生成中文转写，可手动修正' : '仍可正常录音、播放和备份' }}</small></div></section><h2>本地存储</h2><section class="setting-card"><div><strong>存储保护 · {{ storage.persisted ? '已保护' : storage.supported ? '未保护' : '不支持' }}</strong><small>已用 {{ formatBytes(storage.usage) }} / {{ formatBytes(storage.quota) }}</small><span class="meter"><i :style="{ width: `${percent}%` }" /></span><small>保护可降低空间不足时被自动清理的风险，但不能替代备份。</small></div><button v-if="storage.supported && !storage.persisted" type="button" @click="refresh(true)">申请存储保护</button></section><h2>备份与恢复</h2><section class="setting-card actions"><button type="button" :disabled="busy" @click="download">导出 ZIP 备份<small>包含灵感、标签、转写和原始音频</small></button><label>导入 ZIP 备份<small>先完整校验，再写入本地数据</small><input type="file" accept=".zip,application/zip" :disabled="busy" @change="restore" /></label></section><h2>数据管理</h2><section class="setting-card"><button class="danger" type="button" @click="clearAll">清空全部数据<small>此操作无法撤销</small></button></section><p v-if="message" class="success" role="status">{{ message }}</p><p v-if="error" class="error" role="alert">{{ error }}</p></main></template>
<style scoped>.settings-page{display:grid;gap:12px}.settings-page h1,.settings-page h2,.settings-page p{margin:0}.settings-page header p{margin-top:4px;color:#928882;font-size:12px}.settings-page h2{margin-top:8px;font-size:14px}.risk-note{padding:11px;border:1px solid #f1d89f;border-radius:14px;background:#fff8df;color:#806220;font-size:11px;line-height:1.6}.setting-card{overflow:hidden;border:1px solid #eaded7;border-radius:17px;background:#fff}.setting-card>div,.setting-card>button,.setting-card>label{width:100%;min-height:64px;padding:12px;display:grid;gap:5px;border:0;border-bottom:1px solid #eee2da;background:transparent;text-align:left}.setting-card>*:last-child{border-bottom:0}.setting-card small{color:#928882;font-size:10px}.setting-card button,.setting-card label{cursor:pointer}.setting-card input{position:absolute;width:1px;height:1px;opacity:0}.meter{height:8px;overflow:hidden;border-radius:999px;background:#fff0eb}.meter i{height:100%;display:block;border-radius:inherit;background:var(--primary)}.danger{color:#c94d42}.success{color:#27805d;font-size:12px}.error{color:#c94d42;font-size:12px}</style>
